-- Supabase Schema for Connectly Chat App

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop existing tables if they exist (be careful with this in production!)
DROP TABLE IF EXISTS MESSAGES;

DROP TABLE IF EXISTS CHATROOMS;

DROP TABLE IF EXISTS USERS;

-- Users table
CREATE TABLE USERS (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    NAME TEXT NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    AVATAR_URL TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Chatrooms table
CREATE TABLE CHATROOMS (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    USERS UUID[] NOT NULL,
    USERS_DATA JSONB NOT NULL,
    LAST_MESSAGE TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Messages table
CREATE TABLE MESSAGES (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    CHAT_ROOM_ID UUID NOT NULL REFERENCES CHATROOMS(ID) ON DELETE CASCADE,
    SENDER_ID UUID NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    CONTENT TEXT,
    IMAGE_URL TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IDX_MESSAGES_CHAT_ROOM_ID ON MESSAGES(CHAT_ROOM_ID);

CREATE INDEX IDX_MESSAGES_SENDER_ID ON MESSAGES(SENDER_ID);

CREATE INDEX IDX_CHATROOMS_USERS ON CHATROOMS USING GIN(USERS);

-- Enable Row Level Security (RLS)
ALTER TABLE USERS ENABLE ROW LEVEL SECURITY;

ALTER TABLE CHATROOMS ENABLE ROW LEVEL SECURITY;

ALTER TABLE MESSAGES ENABLE ROW LEVEL SECURITY;

-- RLS Policies (adjust based on your auth requirements)
-- Users can only see their own data
CREATE POLICY "Users can view own data" ON USERS
    FOR SELECT USING (AUTH.UID() = ID);

CREATE POLICY "Users can update own data" ON USERS
    FOR UPDATE USING (AUTH.UID() = ID);

-- Allow users to insert their own data (for registration)
CREATE POLICY "Users can insert own data" ON USERS
    FOR INSERT WITH CHECK (AUTH.UID() = ID);

-- Chatrooms policies
CREATE POLICY "Users can view chatrooms they belong to" ON CHATROOMS
    FOR SELECT USING (AUTH.UID() = ANY(USERS));

CREATE POLICY "Users can create chatrooms" ON CHATROOMS
    FOR INSERT WITH CHECK (AUTH.UID() = ANY(USERS));

CREATE POLICY "Users can update chatrooms they belong to" ON CHATROOMS
    FOR UPDATE USING (AUTH.UID() = ANY(USERS));

-- Messages policies
CREATE POLICY "Users can view messages in their chatrooms" ON MESSAGES
    FOR SELECT USING (
        EXISTS (
    SELECT
         1
    FROM
         CHATROOMS
    WHERE
         CHATROOMS.ID = MESSAGES.CHAT_ROOM_ID
        AND AUTH.UID() = ANY(CHATROOMS.USERS)
)
    );

CREATE POLICY "Users can insert messages in their chatrooms" ON MESSAGES
    FOR INSERT WITH CHECK (
        EXISTS (
    SELECT
         1
    FROM
         CHATROOMS
    WHERE
         CHATROOMS.ID = MESSAGES.CHAT_ROOM_ID
        AND AUTH.UID() = ANY(CHATROOMS.USERS)
)
        AND AUTH.UID() = SENDER_ID
    );