-- Supabase Schema for Connectly Chat App (No RLS for initial setup)

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop existing tables if they exist (be careful with this in production!)
DROP TABLE IF EXISTS MESSAGES;

DROP TABLE IF EXISTS CHATROOMS;

DROP TABLE IF EXISTS USERS;

-- Users table
CREATE TABLE USERS (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    NAME TEXT NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    AVATAR_URL TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Chatrooms table
CREATE TABLE CHATROOMS (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    USERS UUID[] NOT NULL,
    USERS_DATA TEXT NOT NULL,
    LAST_MESSAGE TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Messages table
CREATE TABLE MESSAGES (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    CHAT_ROOM_ID UUID NOT NULL REFERENCES CHATROOMS(ID) ON DELETE CASCADE,
    SENDER_ID UUID NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    CONTENT TEXT,
    IMAGE_URL TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IDX_MESSAGES_CHAT_ROOM_ID ON MESSAGES(CHAT_ROOM_ID);

CREATE INDEX IDX_MESSAGES_SENDER_ID ON MESSAGES(SENDER_ID);

CREATE INDEX IDX_CHATROOMS_USERS ON CHATROOMS USING GIN(USERS);

-- Row Level Security is DISABLED for initial setup
-- You can enable and configure RLS policies after testing the app