-- Supabase Schema for Connectly Chat App

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop existing tables if they exist (be careful with this in production!)
DROP TABLE IF EXISTS MESSAGES;

DROP TABLE IF EXISTS CHATROOMS;

DROP TABLE IF EXISTS USERS;

-- Users table
CREATE TABLE USERS (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    NAME TEXT NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    AVATAR_URL TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Chatrooms table
CREATE TABLE CHATROOMS (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    USERS UUID[] NOT NULL,
    USERS_DATA TEXT NOT NULL,
    LAST_MESSAGE TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Messages table
CREATE TABLE MESSAGES (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    CHAT_ROOM_ID UUID NOT NULL REFERENCES CHATROOMS(ID) ON DELETE CASCADE,
    SENDER_ID UUID NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    CONTENT TEXT,
    IMAGE_URL TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IDX_MESSAGES_CHAT_ROOM_ID ON MESSAGES(CHAT_ROOM_ID);

CREATE INDEX IDX_MESSAGES_SENDER_ID ON MESSAGES(SENDER_ID);

CREATE INDEX IDX_CHATROOMS_USERS ON CHATROOMS USING GIN(USERS);

-- Enable Row Level Security (RLS)
ALTER TABLE USERS ENABLE ROW LEVEL SECURITY;

ALTER TABLE CHATROOMS ENABLE ROW LEVEL SECURITY;

ALTER TABLE MESSAGES ENABLE ROW LEVEL SECURITY;

-- Simple RLS Policies that work with Supabase
-- Users policies
CREATE POLICY "Enable all operations for users" ON USERS FOR ALL USING (TRUE);

-- Chatrooms policies - allow all operations (you can restrict later if needed)
CREATE POLICY "Enable all operations for chatrooms" ON CHATROOMS FOR ALL USING (TRUE);

-- Messages policies - allow all operations (you can restrict later if needed)
CREATE POLICY "Enable all operations for messages" ON MESSAGES FOR ALL USING (TRUE);